export const DEPARTAMENTOS = [
  { id: 1, nombre: 'Amazonas' },
  { id: 2, nombre: 'Antioquia' },
  { id: 3, nombre: 'Arauca' },
  { id: 4, nombre: 'Atlántico' },
  { id: 5, nombre: 'Bolívar' },
  { id: 6, nombre: 'Boyacá' },
  { id: 7, nombre: 'Caldas' },
  { id: 8, nombre: 'Caquetá' },
  { id: 9, nombre: 'Casanare' },
  { id: 10, nombre: 'Cauca' },
  { id: 11, nombre: 'Cesar' },
  { id: 12, nombre: 'Chocó' },
  { id: 13, nombre: 'Córdoba' },
  { id: 14, nombre: 'Cundinamarca' },
  { id: 15, nombre: 'Guainía' },
  { id: 16, nombre: 'Guaviare' },
  { id: 17, nombre: 'Huila' },
  { id: 18, nombre: 'La Guajira' },
  { id: 19, nombre: 'Magdalena' },
  { id: 20, nombre: 'Meta' },
  { id: 21, nombre: 'Nariño' },
  { id: 22, nombre: 'Norte de Santander' },
  { id: 23, nombre: 'Putumayo' },
  { id: 24, nombre: 'Quindío' },
  { id: 25, nombre: 'Risaralda' },
  { id: 26, nombre: 'San Andrés y Providencia' },
  { id: 27, nombre: 'Santander' },
  { id: 28, nombre: 'Sucre' },
  { id: 29, nombre: 'Tolima' },
  { id: 30, nombre: 'Valle del Cauca' },
  { id: 31, nombre: 'Vaupés' },
  { id: 32, nombre: 'Vichada' },
];


